#
# CC Creative Commons 2022
# Uznanie autorstwa - Bez utworów zależnych 4.0 Międzynarodowe
# Autor olios
#

#   ___   _      _   _    ___   ___   _  _
#  | _ \ | |    | | | |  / __| |_ _| | \| |
#  |  _/ | |__  | |_| | | (_ |  | |  | .` |
#  |_|   |____|  \___/   \___| |___| |_|\_|
#

# WAŻNE!
# Każde zmiany w tym pliku wymagają przeładowania serwera lub jego restartu
# Usuwanie zmiennych spowoduje niepoprawne działanie pluginu
# Możesz pobrać oryginalnie, niemodyfikowane pliki ze stronie pluginu
# https://www.spigotmc.org/resources/authors/olios123.1116758/

# Dostaniesz powiadomienie, gdy zostanie wypuszczona nowsza wersja pluginu
check-updates: true

# Język pluginu
# Możesz tworzyć własne pliki językowe .yml lub edytować już istniejące
language: en

# Logi pluginu będą wyświetlane w zielonym kolorze
clearer-logs: false

#   _  _     _     ___   ___     ___    ___    ___   ___     __  __    ___    ___    ___
#  | || |   /_\   | _ \ |   \   / __|  / _ \  | _ \ | __|   |  \/  |  / _ \  |   \  | __|
#  | __ |  / _ \  |   / | |) | | (__  | (_) | |   / | _|    | |\/| | | (_) | | |) | | _|
#  |_||_| /_/ \_\ |_|_\ |___/   \___|  \___/  |_|_\ |___|   |_|  |_|  \___/  |___/  |___|
#

# Jeżeli chcesz odbanować gracza wpisz /pardon [gracz]

# Typ bana określa, czy bany z czasem mają być coraz dłuższe, czy ich długość ma zawsze być taka sama
ban-type: "increasing" # Czas każdego bana jest coraz dłuższy
#ban-type: "constant" # Czas każdego bana jest taki sam

# //------------------------\\
# |  Constant konfiguracja   |
# \\------------------------//

# Czas bana w minutach
# Używane, jeżeli w ustawieniu "ban-type" wybrano "constant"
# Możesz ustawić też czas w minutach i sekundach
# Na przykładzie: 15.5 - ban będzie trwał 15 minut i 30 sekund
# Wartość po kropce określa część minuty
ban-time: 15
#ban-time: 15.5 # 15min 30sec

# Długość bana zależna od rangi
# Używane, gdy wybrałeś "constant" w sekcji "ban-type"
# Długość bana podaj w minutach
# Aby plugin rozpoznał, że gracz ma wskazaną rangę należy dodać mu permisje z nazwą rangi
# Na przykład: vip: 15 -> permisja "vip"
# Plugin sprawdza od najwyższej (najniższa pozycja) do najniższej rangi
# Plugin wymaga, aby zachować wartość "default" - nie zmieniaj nazwy tej zmiennej
ban-rank-time:
  enable: false # true - włączony / false - wyłączony
  ranks:
    default: 15
    vip: 10
    mvip: 5
    admin: 0 # Gracz nie otrzyma bana

# //-------------------------\\
# |  Increasing konfiguracja  |
# \\-------------------------//

# Długości banów
# Używane, jeżeli w ustawieniu "ban-type" wybrano "increasing"
# Czas bana powinien zostać podany w minutach
# Gracz po każdej kolejnej śmierci będzie otrzymywał coraz dłuższy czas bana
#
#        1:                 15
#  numer śmierci      czas w minutach
#
# Inny przykład z sekundami: 15.5 - 15 minut i 30 sekund
#
ban-length:
  1: 15 # 15min
  2: 30 # 30min
  3: 60 # 1h
  4: 360 # 6h
  5: 1440 # 24h
  #1: 15.5 # 15min 30sec

# Długość bana zależna od rangi
# Używane, gdy wybrano "increasing" w sekcji "ban-type"
# Gracz po każdej kolejnej śmierci będzie otrzymywał coraz dłuższy czas bana
# Aby plugin rozpoznał, że gracz ma wskazaną rangę należy dodać mu permisje z nazwą rangi
# Na przykład: vip: 15 -> permisja "vip"
# Gracze bez rangi będą przypisani do grupy "default"
# Plugin sprawdza od najwyższej (najniższa pozycja) do najniższej rangi
# Plugin wymaga, aby zachować wartość "default" - nie zmieniaj nazwy tej zmiennej
ban-rank-length:
  enable: false # true - włączone / false - wyłączone
  ranks:
    # default
    default:
      1: 15 # 15min
      2: 30 # 30min
      3: 60 # 1h
      4: 360 # 6h
      5: 1440 # 24h

    # vip
    vip:
      1: 10 # 10min
      2: 20 # 20min
      3: 45 # 45min
      4: 300 # 5h
      5: 1200 # 20h

    # mvip
    mvip:
      1: 5 # 5min
      2: 15 # 15min
      3: 30 # 30min
      4: 240 # 4h
      5: 960 # 16h

    # admin
    admin:
      1: 0 # Gracz nie zostanie zbanowany

# //---------------------------\\
# | Konfiguracja poziomów banów |
# \\---------------------------//

# Zmniejszanie długości bana
# Jeżeli gracz od dłuższego czasu nie zginie, jego poziom bana zostanie obniżony
lowering-ban:
  enable: true # default true
  time-without-death: 360 # Czas bez bana aby obniżyć jego poziom - default 360min (6h) (możesz używać sekund np. 360.5 - 360min i 30sec)
  lowered-level: 1 # Ilość o ile poziomów obniży się poziom bana

# //-------------------------\\
# |    Lives configuration    |
# \\-------------------------//

# Gracz przed zbanowaniem może mieć wilka żyć
# Gdy gracz zginie traci jedno ze swoich żyć, a gdy nie ma och już więcej zostaje zbanowany
lives:
  enable: true # true - włączone / false - wyłączone

  # Określ czy gracz może włączać i wyłączać informacje o ilości swoich żyć
  toggle-info: true
  default-visible: true # Ustal, czy gracz ma widzieć swoje życia od razu po wejściu na serwer, czy będzie musiał je włączyć

  # Informacja o życiach gracza, będzie wyświetlona ona nad paskiem ekwipunku
  bar-info: "&c> &4> &c>   ❤ ${lives} &fŻycia &c❤   < &4< &c<"

  # Standardowa ilość żyć
  default-count: 3

  # Odnawianie żyć - gracz po odpowiednim czasie od śmierci może otrzymać życie
  # Ilość dodanych żyć nigdy nie będzie większa niż ich standardowa ilość
  renewing-lives:
    enable: true # true - włączone / false - wyłączone
    time-without-death: 360 # Czas bez śmierci, aby otrzymać życie (standardowo 360min = 6h)

#   ___    ___    ___      _   ___       _     ___    __  __   ___   _  _   ___   ___   _____   ___     _     _____    ___    ___     _
#  / _ \  | _ \  / __|  _ | | | __|     /_\   |   \  |  \/  | |_ _| | \| | |_ _| / __| |_   _| | _ \   /_\   |_   _|  / _ \  | _ \   /_\
# | (_) | |  _/ | (__  | || | | _|     / _ \  | |) | | |\/| |  | |  | .` |  | |  \__ \   | |   |   /  / _ \    | |   | (_) | |   /  / _ \
#  \___/  |_|    \___|  \__/  |___|   /_/ \_\ |___/  |_|  |_| |___| |_|\_| |___| |___/   |_|   |_|_\ /_/ \_\   |_|    \___/  |_|_\ /_/ \_\
#

# Nie przyznawaj bana, jeśli gracz, który zginie będzie administratorem (op'em)
admin-no-ban-after-death: false

# Nie przyznawaj bana, jeżeli gracz, który zginie będzie miał tę permisję
# Musisz dać permisję *hardcoremode.nodeath* graczowi
# Gracz nie straci życia ani nie zostanie zbanowany

#    ___   ____    _     _____
#   / __| |_  /   /_\   |_   _|
#  | (__   / /   / _ \    | |
#   \___| /___| /_/ \_\   |_|
#

# Wyślij informację o śmierci gracza na czacie (wpisz null, aby wyłączyć lub pozostaw to miejsce puste)
death-message: "&4&lHardcore Mode |&r &cGracz &f&l${player} &czginął i może powrócić na serwer za &f&l${time}"

# Po powrocie na serwer wyślij informację graczowi o jego następnym czasie bana (wpisz null, aby wyłączyć lub pozostaw to miejsce puste)
next-death-info-message: "&4&lHardcore Mode |&r &cTwój czas śmierci minął. Następna długość bana będzie wynosiła &f&l${time}"

# Informacja o banie
ban-reason:
  - "&4&lHardcore Mode"
  - "&r&cZginąłeś i zostałeś zbanowany na czas &f&l${time}"
  - "&cBan kończy się &f&l${date}"
  - ""
  - "${reason}"

#
# TA OPCJA MOŻE ZAWIERAĆ BŁĘDY ZWIĄZANE Z DOSTĘPEM DO ZABÓJCY GRACZA
#
# Powody zginięcia
# Aby ta opcja była używana musi zostać włączona
# W przeciwnym razie plugin wyśle wiadomość "death-message"
death-reason-enable: true
death-reason:
  # Gdy gracz zostanie zbanowany
  BLOCK_EXPLOSION:      "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fwybuchł &ci może powrócić na serwer za &f&l${time}"
  CONTACT:              "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zakuty na śmierć &ci może powrócić na serwer za &f&l${time}"
  DRAGON_BREATH:        "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął od odechu smoka &ci może powrócić na serwer za &f&l${time}"
  DROWNING:             "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &futonął &ci może powrócić na serwer za &f&l${time}"
  ENTITY_ATTACK:        "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zabity przez: ${killer} &ci może powrócić na serwer za &f&l${time}"
  ENTITY_EXPLOSION:     "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął od wybuchu &ci może powrócić na serwer za &f&l${time}"
  FALL:                 "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fspadł z wysokiego miejsca &ci może powrócić na serwer za &f&l${time}"
  FALLING_BLOCK:        "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginał od updaku bloku &ci może powrócić na serwer za &f&l${time}"
  FIRE:                 "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fspłonął żywcem &ci może powrócić na serwer za &f&l${time}"
  FIRE_TICK:            "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fspłonął żywcem &ci może powrócić na serwer za &f&l${time}"
  FLY_INTO_WALL:        "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fwleciał w ścianę &ci może powrócić na serwer za &f&l${time}"
  FREEZE:               "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzamroził się &ci może powrócić na serwer za &f&l${time}"
  HOT_FLOOR:            "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fodkrył, że podłoga to lawa &ci może powrócić na serwer za &f&l${time}"
  LAVA:                 "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fpróbował pływać w lawie &ci może powrócić na serwer za &f&l${time}"
  LIGHTNING:            "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał porażony piorunem &ci może powrócić na serwer za &f&l${time}"
  MAGIC:                "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zabity przy pomocy magii przez: ${killer} &ci może powrócić na serwer za &f&l${time}"
  POISON:               "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał otruty &ci może powrócić na serwer za &f&l${time}"
  PROJECTILE:           "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zastrzelony przez: ${killer} &ci może powrócić na serwer za &f&l${time}"
  SONIC_BOOM:           "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął od fali uderzeniowej &ci może powrócić na serwer za &f&l${time}"
  STARVATION:           "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzmarł z głodu &ci może powrócić na serwer za &f&l${time}"
  SUFFOCATION:          "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zamurowany w ścianie &ci może powrócić na serwer za &f&l${time}"
  SUICIDE:              "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fpopełnił samobójstwo &ci może powrócić na serwer za &f&l${time}"
  THORNS:               "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął próbując zranić: ${killer} &ci może powrócić na serwer za &f&l${time}"
  VOID:                 "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fwypadł po za świat &ci może powrócić na serwer za &f&l${time}"
  WITHER:               "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fobumarł &ci może powrócić na serwer za &f&l${time}"
  OTHER:                "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął &ci może powrócić na serwer za &f&l${time}"

  # Gdy gracz nie zostanie zbanowany
  NO_BAN_BLOCK_EXPLOSION:   "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fwybuchł &cale nie został zbanowany"
  NO_BAN_CONTACT:           "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zakuty na śmierć &cale nie został zbanowany"
  NO_BAN_DRAGON_BREATH:     "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął od odechu smoka &cale nie został zbanowany"
  NO_BAN_DROWNING:          "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &futonął &cale nie został zbanowany"
  NO_BAN_ENTITY_ATTACK:     "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zabity przez: ${killer} &cale nie został zbanowany"
  NO_BAN_ENTITY_EXPLOSION:  "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął od wybuchu &cale nie został zbanowany"
  NO_BAN_FALL:              "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fspadł z wysokiego miejsca &cale nie został zbanowany"
  NO_BAN_FALLING_BLOCK:     "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginał od updaku bloku &cale nie został zbanowany"
  NO_BAN_FIRE:              "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fspłonął żywcem &cale nie został zbanowany"
  NO_BAN_FIRE_TICK:         "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fspłonął żywcem &cale nie został zbanowany"
  NO_BAN_FLY_INTO_WALL:     "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fwleciał w ścianę &cale nie został zbanowany"
  NO_BAN_FREEZE:            "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzamroził się &cale nie został zbanowany"
  NO_BAN_HOT_FLOOR:         "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fodkrył, że podłoga to lawa &cale nie został zbanowany"
  NO_BAN_LAVA:              "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fpróbował pływać w lawie &cale nie został zbanowany"
  NO_BAN_LIGHTNING:         "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał porażony piorunem &cale nie został zbanowany"
  NO_BAN_MAGIC:             "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zabity przy pomocy magii przez: ${killer} &cale nie został zbanowany"
  NO_BAN_POISON:            "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał otruty &cale nie został zbanowany"
  NO_BAN_PROJECTILE:        "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zastrzelony przez: ${killer} &cale nie został zbanowany"
  NO_BAN_SONIC_BOOM:        "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął od fali uderzeniowej &cale nie został zbanowany"
  NO_BAN_STARVATION:        "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzmarł z głodu &cale nie został zbanowany"
  NO_BAN_SUFFOCATION:       "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzostał zamurowany w ścianie &cale nie został zbanowany"
  NO_BAN_SUICIDE:           "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fpopełnił samobójstwo &cale nie został zbanowany"
  NO_BAN_THORNS:            "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął próbując zranić: ${killer} &cale nie został zbanowany"
  NO_BAN_VOID:              "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fwypadł po za świat &cale nie został zbanowany"
  NO_BAN_WITHER:            "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fobumarł &cale nie został zbanowany"
  NO_BAN_OTHER:             "&7[&4&lHardcore &c&lMode&r&7] &r &cGracz &f&l${player} &fzginął &cale nie został zbanowany"

# BLOCK_EXPLOSION   - Śmierć spowodowana przebywaniem w obszarze, gdzie eksploduje blok.
# CONTACT           - Śmierć spowodowana, gdy gracz zetknie się z blokiem takim jak Kaktus, Dripstone (Stalagmit) lub Berry Bush.
# DRAGON_BREATH     - Śmierć spowodowana przez smoka ziejącego ogniem.
# DROWNING          - Śmierć spowodowana brakiem powietrza w wodzie.
# ENTITY_ATTACK     - Śmierć spowodowana atakiem przez inną istotę (potwór/gracz).
# ENTITY_EXPLOSION  - Śmierć spowodowana przebywaniem w obszarze, gdy istota, taka jak Creeper, eksploduje.
# FALL              - Śmierć spowodowana upadkiem z wysokości.
# FALLING_BLOCK     - Śmierć spowodowana uderzeniem spadającym klockiem, który zadaje obrażenia.
# FIRE              - Śmierć spowodowana bezpośrednim wystawieniem na działanie ognia.
# FIRE_TICK         - Śmierć spowodowana oparzeniami spowodowanymi ogniem.
# FLY_INTO_WALL     - Śmierć spowodowana przez uderzenie w ścianę (elytra).
# FREEZE            - Śmierć spowodowana zamarzaniem.
# HOT_FLOOR         - Śmierć spowodowana, gdy gracz nadepnie na Material.MAGMA_BLOCK.
# LAVA              - Śmierć spowodowana bezpośrednim kontaktem z lawą.
# LIGHTNING         - Śmierć spowodowana uderzeniem pioruna.
# MAGIC             - Śmierć spowodowana trafieniem przez miksturę obrażeń lub zaklęcie.
# POISON            - Śmierć spowodowana przez trwający efekt trucizny.
# PROJECTILE        - Śmierć spowodowana od pocisku (strzała itp.).
# SONIC_BOOM        - Śmierć spowodowana atakiem Sonic Boom od Strażnika.
# STARVATION        - Śmierć spowodowana głodem z powodu pustego paska głodu.
# SUFFOCATION       - Śmierć spowodowana przez uduszenie w ścianie.
# SUICIDE           - Sambójstwo.
# THORNS            - Śmierć spowodowana odwetem na atak zaklęcia Ciernie.
# VOID              - Śmierć spowodowana wypadnięciem poza świat.
# WITHER            - Śmierć spowodowana efektem mikstury Wither.
# OTHER             - Śmierć spowodowana przez inne przyczyny.

#   ___   ___   ___   _  __  _____  __   __
#  | __| | __| | __| | |/ / |_   _| \ \ / /
#  | _|  | _|  | _|  | ' <    | |    \ V /
#  |___| |_|   |___| |_|\_\   |_|     |_|
#

# Gdy gracz zginie pokaż piorun w miejscu jego śmierci
death-lightning: true